<ShoppingCartItem@OneLineAvatarIconListItem>
    MDLabel:
        text: "0"
        id: amount
        theme_text_color: "Custom"
        pos_hint: {"center_x": 0.53,"center_y":0.5}
        text_color: 1, 1, 1, 1
        font_size: '25sp'

    MDLabel:
        id: buyer
        text: "mail"
        theme_text_color: "Custom"
        pos_hint: {"center_x": 0.45,"center_y":0.5}
        halign: "right"
        text_color: 1, 1, 1, 1
        font_size: '17sp'