<ShoppingCartItem@OneLineAvatarIconListItem>
    MDLabel:
        text: "0"
        id: amount
        theme_text_color: "Custom"
        pos_hint: {"center_x": 0.54,"center_y":0.5}
        text_color: 1, 1, 1, 1
        font_size: '25sp'

    MDLabel:
        id: buyer
        text: "mailadress"
        theme_text_color: "Custom"
        pos_hint: {"center_x": 1.0,"center_y":0.5}
        text_color: 1, 1, 1, 1
        font_size: '13sp'